title = "Liveboat feed page"
site_path = "/"
show_read_articles = true
newsboat_urls_file = "test_data/urls"
newsboat_cache_file = "cache.db"
time_threshold = 20
build_dir = "liveboat_build"
template_name = "default"
